/*
 * File: "rpc_remote.c".
 * Do NOT edit this file!
 * This file is autogenerated from "rpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "rpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include "rpc_client_dbg.h" // VSRPC_ERROR_DBG()
#include "rpc_client.h" // rpc_*_call(), rpc_*_wait()
//----------------------------------------------------------------------------
int rpc_atoi_remote(vsrpc_t* rpc, char* a1)
{ // VSRPC wrapper on "client" side
  int err; int a0;

  // call remote procedure
  err = rpc_atoi_call(rpc, a1);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return 0; }

  // wait then remote procedure finish
  err = rpc_atoi_wait(rpc, &a0);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return 0; }

  return a0;
}
//----------------------------------------------------------------------------
void rpc_test_remote(vsrpc_t* rpc, int a1)
{ // VSRPC wrapper on "client" side
  int err;

  // call remote procedure
  err = rpc_test_call(rpc, a1);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  // wait then remote procedure finish
  err = rpc_test_wait(rpc);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  return;
}
//----------------------------------------------------------------------------
void rpc_cap_remote(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side
  int err;

  // call remote procedure
  err = rpc_cap_call(rpc);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  // wait then remote procedure finish
  err = rpc_cap_wait(rpc);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  return;
}
//----------------------------------------------------------------------------
void rpc_loop_remote(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side
  int err;

  // call remote procedure
  err = rpc_loop_call(rpc);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  // wait then remote procedure finish
  err = rpc_loop_wait(rpc);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  return;
}
//----------------------------------------------------------------------------
void rpc_toall_remote(vsrpc_t* rpc, char* a1)
{ // VSRPC wrapper on "client" side
  int err;

  // call remote procedure
  err = rpc_toall_call(rpc, a1);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  // wait then remote procedure finish
  err = rpc_toall_wait(rpc);
  if (err != VSRPC_ERR_NONE)
  { VSRPC_ERROR_DBG(err, rpc) return; }

  return;
}
//----------------------------------------------------------------------------
