/*
 * File: "rpc_remote.h".
 * Do NOT edit this file!
 * This file is autogenerated from "rpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "rpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include "vsrpc.h"
//----------------------------------------------------------------------------
int rpc_atoi_remote(vsrpc_t*, char*);
void rpc_test_remote(vsrpc_t*, int);
void rpc_cap_remote(vsrpc_t*);
void rpc_loop_remote(vsrpc_t*);
void rpc_toall_remote(vsrpc_t*, char*);
//----------------------------------------------------------------------------
