/*
 * File: "rpc_client.c".
 * Do NOT edit this file!
 * This file is autogenerated from "rpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "rpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include "vsrpc.h"
//----------------------------------------------------------------------------
int rpc_atoi_call(vsrpc_t* rpc, char* a1)
{ // VSRPC wrapper on "client" side (call remote procedure)
  return vsrpc_call_ex(rpc, "ss", "atoi", a1);
}
//----------------------------------------------------------------------------
int rpc_atoi_wait(vsrpc_t* rpc, int* a0)
{ // VSRPC wrapper on "client" side (wait when remote procedure finish)
  int retv = vsrpc_wait(rpc);
  if (retv != VSRPC_ERR_NONE)
  {
    if (rpc->retc != 0)
    { vsrpc_free_argv(rpc->retv); rpc->retc = 0; }
  }
  else if (rpc->retc != 1) retv = VSRPC_ERR_BARG;
  if (retv != VSRPC_ERR_NONE)
  {
    *a0 = 0;
    return retv;
  }
  *a0 = vsrpc_str2int(rpc->retv[0]);
#if 1 != 0
  vsrpc_free_argv(rpc->retv); rpc->retc = 0;
#endif
  return VSRPC_ERR_NONE;
}
//----------------------------------------------------------------------------
int rpc_test_call(vsrpc_t* rpc, int a1)
{ // VSRPC wrapper on "client" side (call remote procedure)
  return vsrpc_call_ex(rpc, "si", "test", a1);
}
//----------------------------------------------------------------------------
int rpc_test_wait(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side (wait when remote procedure finish)
  int retv = vsrpc_wait(rpc);
  if (retv != VSRPC_ERR_NONE)
  {
    if (rpc->retc != 0)
    { vsrpc_free_argv(rpc->retv); rpc->retc = 0; }
  }
  else if (rpc->retc != 0) retv = VSRPC_ERR_BARG;
  if (retv != VSRPC_ERR_NONE)
  {
    return retv;
  }
#if 0 != 0
  vsrpc_free_argv(rpc->retv); rpc->retc = 0;
#endif
  return VSRPC_ERR_NONE;
}
//----------------------------------------------------------------------------
int rpc_cap_call(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side (call remote procedure)
  return vsrpc_call_ex(rpc, "s", "cap");
}
//----------------------------------------------------------------------------
int rpc_cap_wait(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side (wait when remote procedure finish)
  int retv = vsrpc_wait(rpc);
  if (retv != VSRPC_ERR_NONE)
  {
    if (rpc->retc != 0)
    { vsrpc_free_argv(rpc->retv); rpc->retc = 0; }
  }
  else if (rpc->retc != 0) retv = VSRPC_ERR_BARG;
  if (retv != VSRPC_ERR_NONE)
  {
    return retv;
  }
#if 0 != 0
  vsrpc_free_argv(rpc->retv); rpc->retc = 0;
#endif
  return VSRPC_ERR_NONE;
}
//----------------------------------------------------------------------------
int rpc_loop_call(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side (call remote procedure)
  return vsrpc_call_ex(rpc, "s", "loop");
}
//----------------------------------------------------------------------------
int rpc_loop_wait(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side (wait when remote procedure finish)
  int retv = vsrpc_wait(rpc);
  if (retv != VSRPC_ERR_NONE)
  {
    if (rpc->retc != 0)
    { vsrpc_free_argv(rpc->retv); rpc->retc = 0; }
  }
  else if (rpc->retc != 0) retv = VSRPC_ERR_BARG;
  if (retv != VSRPC_ERR_NONE)
  {
    return retv;
  }
#if 0 != 0
  vsrpc_free_argv(rpc->retv); rpc->retc = 0;
#endif
  return VSRPC_ERR_NONE;
}
//----------------------------------------------------------------------------
int rpc_toall_call(vsrpc_t* rpc, char* a1)
{ // VSRPC wrapper on "client" side (call remote procedure)
  return vsrpc_call_ex(rpc, "ss", "toall", a1);
}
//----------------------------------------------------------------------------
int rpc_toall_wait(vsrpc_t* rpc)
{ // VSRPC wrapper on "client" side (wait when remote procedure finish)
  int retv = vsrpc_wait(rpc);
  if (retv != VSRPC_ERR_NONE)
  {
    if (rpc->retc != 0)
    { vsrpc_free_argv(rpc->retv); rpc->retc = 0; }
  }
  else if (rpc->retc != 0) retv = VSRPC_ERR_BARG;
  if (retv != VSRPC_ERR_NONE)
  {
    return retv;
  }
#if 0 != 0
  vsrpc_free_argv(rpc->retv); rpc->retc = 0;
#endif
  return VSRPC_ERR_NONE;
}
//----------------------------------------------------------------------------
