/*
 * File: "rpc_client.h".
 * Do NOT edit this file!
 * This file is autogenerated from "rpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "rpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include "vsrpc.h"
//----------------------------------------------------------------------------
int rpc_atoi_call(vsrpc_t*, char*);
int rpc_atoi_wait(vsrpc_t*, int*);
int rpc_test_call(vsrpc_t*, int);
int rpc_test_wait(vsrpc_t*);
int rpc_cap_call(vsrpc_t*);
int rpc_cap_wait(vsrpc_t*);
int rpc_loop_call(vsrpc_t*);
int rpc_loop_wait(vsrpc_t*);
int rpc_toall_call(vsrpc_t*, char*);
int rpc_toall_wait(vsrpc_t*);
//----------------------------------------------------------------------------
