/*
 * File: "lrpc_server.c".
 * Do NOT edit this file!
 * This file is autogenerated from "lrpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "lrpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include <stdlib.h> // NULL
#include "lrpc_local.h"
//----------------------------------------------------------------------------
char **lrpc_fn_msg(vsrpc_t* rpc, int argc, char * const argv[])
{ // VSRPC wrapper on "server" side
  char **retv;
  char* a1;

  // check number of arguments
  if (argc != 2) return NULL;

  // call procedure
  a1 = argv[1];
  lrpc_msg(rpc, a1);

  // fill output array
  retv = vsrpc_list2argv("");
  return retv; // return values :-D
}
//----------------------------------------------------------------------------
vsrpc_func_t lrpc_vsrpc_func[] = {
  { "msg", lrpc_fn_msg },
  { NULL, NULL }
};
//----------------------------------------------------------------------------
