/*
 * File: "lrpc_local.h".
 * Do NOT edit this file!
 * This file is autogenerated from "lrpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "lrpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include "vsrpc.h"
//----------------------------------------------------------------------------
void lrpc_msg(vsrpc_t*, char*);
//----------------------------------------------------------------------------
