/*
 * File: "lrpc_server.h".
 * Do NOT edit this file!
 * This file is autogenerated from "lrpc.vsidl" file
 * on "12.03.2019 11:42:03" and may be overwriten.
 * Please edit "lrpc.vsidl" file.
 */
//----------------------------------------------------------------------------
#include "vsrpc.h"
//----------------------------------------------------------------------------
extern vsrpc_func_t lrpc_vsrpc_func[];
//----------------------------------------------------------------------------
